name: deploy-main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          cat >>~/.ssh/config <<END
          Host 52.79.203.42
            HostName $EC2_HOST
            User $EC2_USER
            IdentityFile ~/.ssh/id_rsa
            StrictHostKeyChecking no
          END
        env:
          EC2_USER: ubuntu
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy Workspace
        run: |
          ssh 52.79.203.42 'sudo mkdir -p /opt/app'
          ssh 52.79.203.42 'sudo chown ubuntu:ubuntu /opt/app'
          scp -r ./[!.]* 52.79.203.42:/opt/app

      - name: Install dependencies
        run: |
          ssh 52.79.203.42 'npm install --prefix /opt/app/'

      - name: Copy systemd service file
        run: |
          ssh 52.79.203.42 '
            echo "[Unit]
            Description=UMC 7th Project
            After=network.target

            [Service]
            User=${USER}
            ExecStart=/usr/bin/npm run dev --prefix /opt/app/
            Restart=always

            [Install]
            WantedBy=multi-user.target" | sudo tee /etc/systemd/system/app.service
          '

      - name: Enable systemd service
        run: |
          ssh 52.79.203.42 'sudo systemctl daemon-reload'
          ssh 52.79.203.42 'sudo systemctl enable app'

      - name: Restart systemd service
        run: |
          ssh 52.79.203.42 'sudo systemctl restart app'